### ISSUE TITLE
The test dice of prostate dataset is low

### ISSUE THREAD

**Issue by ChangJoey56** [lambert-x/CateNorm#1]
Hi~ I try to run the baseline method as "python train.py  --save-fold=Prostate-Single-A --batch-size=4 --sitename A --epochs=20", but the test dice of site B or site C using this trained model is very low, which is 0.5913 and 0.247.

**Comment by lambert-x** [comment]
The result makes sense as the training data only comes from **site A (defined by argument --sitename)**. There are domain gaps between different sites, so the performance would be low on other sites. If you want to follow the multi-domain setting in the paper, please modify **--sitename A** to **--sitename ABC**  (this is for prostate experiments).

**Comment by ChangJoey56** [comment]
Thanks for your kind reply. But the results of baseline under single-domain
setting described in the paper are  88.69, 85.2,  and 87.21 respectively.
There exists a large gap between the results from papers and the results
tested by myself. I guess there may be some details I have missed. Could
you offer me more details about this? Thanks in advance.
[image: image.png]

lambert-x ***@***.***> 于2021年7月24日周六 上午2:40写道：

**Comment by lambert-x** [comment]
The results with single-domain setting are **trained and tested on data from the same site** (i.e. train A, test A; train B, test B). So, for the experiment `python train.py --save-fold=Prostate-Single-A --batch-size=4 --sitename A --epochs=20`, **it is just for reproducing the results on site A** (**the results on site B and site C** are **just for showing the domain gap**).  You need to **modify the --sitename argument to B/C** to experiment with other sites.

**Comment by ChangJoey56** [comment]
I'm sorry for misunderstanding the meaning of "single-domain setting".  I
will try and follow the given steps later. Thanks for your prompt response
and it does benefit my research a lot.

lambert-x ***@***.***> 于2021年7月26日周一 上午4:22写道：
